# Generated by Django 4.0.2 on 2022-03-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('computer_literate', models.TextField()),
                ('income', models.TextField()),
            ],
        ),
    ]
