# Generated by Django 4.0.3 on 2022-03-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, help_text='254 characters or fewer. Must be a valid email address.', max_length=254, unique=True, verbose_name='email')),
                ('address', models.CharField(max_length=150)),
                ('computer_literate', models.BooleanField(default=True, verbose_name='active')),
                ('income', models.CharField(max_length=150)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
